# Generated by Django 2.2.1 on 2019-05-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iddomicilio', models.IntegerField(default=170)),
                ('idcliente', models.IntegerField(default=170)),
                ('idfactura', models.IntegerField(default=170)),
            ],
        ),
    ]
