# Generated by Django 2.2.1 on 2019-05-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idproducto', models.IntegerField(default=170)),
                ('valor_cupon', models.IntegerField(default=170)),
            ],
        ),
    ]
