# Generated by Django 2.2.1 on 2019-05-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
                ('cedula', models.IntegerField(default=170)),
                ('direccion', models.CharField(max_length=120)),
                ('edad', models.IntegerField(default=170)),
            ],
        ),
    ]
